export interface Station {
  code: string;
  name: string;
}

export const STATIONS: Station[] = [
  { code: "NDLS", name: "New Delhi" },
  { code: "HWH", name: "Howrah Jn" },
  { code: "CSMT", name: "C Shivaji Maharaj T" },
  { code: "MAS", name: "Mgr Chennai Central" },
  { code: "SBC", name: "Ksr Bengaluru" },
  { code: "ADI", name: "Ahmedabad Jn" },
  { code: "PUNE", name: "Pune Jn" },
  { code: "SEC", name: "Secunderabad Jn" },
  { code: "JP", name: "Jaipur" },
  { code: "LKO", name: "Lucknow Nr" },
  { code: "CNB", name: "Kanpur Central" },
  { code: "PAT", name: "Patna Jn" },
  { code: "BCT", name: "Mumbai Central" },
  { code: "MMCT", name: "Mumbai Central" },
  { code: "BVI", name: "Borivali" },
  { code: "BDTS", name: "Mumbai Bandra Terminus" },
  { code: "DR", name: "Mumbai Dadar Central" },
  { code: "DDR", name: "Mumbai Dadar Western" },
  { code: "LTT", name: "Lokmanyatilak T" },
  { code: "KYN", name: "Kalyan Jn" },
  { code: "TNA", name: "Thane" },
  { code: "PNVL", name: "Panvel" },
  { code: "NGP", name: "Nagpur" },
  { code: "BPL", name: "Bhopal Jn" },
  { code: "JHS", name: "Jhansi Jn" },
  { code: "GWL", name: "Gwalior" },
  { code: "AGC", name: "Agra Cantt" },
  { code: "MTJ", name: "Mathura Jn" },
  { code: "NZM", name: "H Nizamuddin" },
  { code: "ANVT", name: "Anand Vihar Trm" },
  { code: "DLI", name: "Old Delhi" },
  { code: "DEE", name: "Delhi Sarai Rohilla" },
  { code: "BSB", name: "Varanasi Jn" },
  { code: "DDU", name: "Pt Deen Dayal Upadhyaya Jn" },
  { code: "ALD", name: "Allahabad Jn" },
  { code: "PRYJ", name: "Prayagraj Jn" },
  { code: "GKP", name: "Gorakhpur Jn" },
  { code: "ASR", name: "Amritsar Jn" },
  { code: "LDH", name: "Ludhiana Jn" },
  { code: "CDG", name: "Chandigarh" },
  { code: "UMB", name: "Ambala Cant Jn" },
  { code: "JAT", name: "Jammu Tawi" },
  { code: "SVDK", name: "Smvd Katra" },
  { code: "HW", name: "Haridwar Jn" },
  { code: "DDN", name: "Dehradun" },
  { code: "KOTA", name: "Kota Jn" },
  { code: "ST", name: "Surat" },
  { code: "BRC", name: "Vadodara Jn" },
  { code: "RJT", name: "Rajkot Jn" },
  { code: "OKHA", name: "Okha" },
  { code: "INDB", name: "Indore Jn Bg" },
  { code: "JBP", name: "Jabalpur" },
  { code: "BSP", name: "Bilaspur Jn" },
  { code: "R", name: "Raipur Jn" },
  { code: "BBS", name: "Bhubaneswar" },
  { code: "PURI", name: "Puri" },
  { code: "CTC", name: "Cuttack" },
  { code: "VSKP", name: "Visakhapatnam" },
  { code: "BZA", name: "Vijayawada Jn" },
  { code: "TPTY", name: "Tirupati" },
  { code: "RU", name: "Renigunta Jn" },
  { code: "MS", name: "Chennai Egmore" },
  { code: "TBM", name: "Tambaram" },
  { code: "CBE", name: "Coimbatore Jn" },
  { code: "ED", name: "Erode Jn" },
  { code: "SA", name: "Salem Jn" },
  { code: "MDU", name: "Madurai Jn" },
  { code: "TEN", name: "Tirunelveli" },
  { code: "CAPE", name: "Kanyakumari" },
  { code: "TVC", name: "Trivandrum Cntl" },
  { code: "ERS", name: "Ernakulam Jn" },
  { code: "ERN", name: "Ernakulam Town" },
  { code: "CLT", name: "Kozhikode" },
  { code: "MAQ", name: "Mangalore Cntl" },
  { code: "MAJN", name: "Mangalore Jn" },
  { code: "KAWR", name: "Karwar" },
  { code: "MAO", name: "Madgaon" },
  { code: "KRMI", name: "Karmali" },
  { code: "RN", name: "Ratnagiri" },
  { code: "HWH", name: "Howrah Jn" },
  { code: "SDAH", name: "Sealdah" },
  { code: "KOAA", name: "Kolkata" },
  { code: "SHM", name: "Shalimar" },
  { code: "KGP", name: "Kharagpur Jn" },
  { code: "TATA", name: "Tatanagar Jn" },
  { code: "RNC", name: "Ranchi" },
  { code: "DHN", name: "Dhanbad Jn" },
  { code: "GAYA", name: "Gaya Jn" },
  { code: "GHY", name: "Guwahati" },
  { code: "DBRG", name: "Dibrugarh" },
  { code: "NJP", name: "New Jalpaiguri" },
  { code: "KIR", name: "Katihar Jn" },
  { code: "MFP", name: "Muzaffarpur Jn" },
  { code: "SPJ", name: "Samastipur Jn" },
  { code: "BJU", name: "Barauni Jn" },
  { code: "DNR", name: "Danapur" },
  { code: "PPTA", name: "Patliputra" },
];
